services:

  postgres:
    image: pgvector/pgvector:pg17
    container_name: law-copilot-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: law_copilot
      POSTGRES_USER: law_copilot
      POSTGRES_PASSWORD: law_copilot

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U law_copilot -d law_copilot"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  minio:
    image: quay.io/minio/minio:latest
    container_name: law-copilot-minio
    restart: unless-stopped

    command: server /data --console-address ":9001"

    environment:
      MINIO_ROOT_USER: law_copilot
      MINIO_ROOT_PASSWORD: law_copilot_password

    ports:
      - "9000:9000"
      - "9001:9001"

    volumes:
      - minio_data:/data


volumes:
  postgres_data:
  minio_data: